language: python
python:
  - "2.7"
services:
  - redis-server
before_install:
  - export PIP_USE_MIRRORS=true
install:
  - pip install -e .
  - pip install -r requirements/tests.txt Django==$DJANGO
script:
  - django-admin.py test --settings=app_metrics.tests.settings app_metrics
env:
  - DJANGO=1.6.11
  - DJANGO=1.7.11
  - DJANGO=1.8.18
  - DJANGO=1.9.13
  - DJANGO=1.10.8
