language: python
python:
  - "2.7"
  - "3.4"
services:
  - redis-server
before_install:
  - export PIP_USE_MIRRORS=true
matrix:
    fast_finish: true
    include:
      - python: "3.6"
        env: DJANGO=1.11.13
      - python: "3.5"
        env: DJANGO=1.11.13
      - python: "3.5"
        env: DJANGO=1.10.8
      - python: "3.4"
        env: DJANGO=1.10.8
      - python: "3.5"
        env: DJANGO=1.9.13
      - python: "3.5"
        env: DJANGO=1.8.19
      - python: "3.3"
        env: DJANGO=1.8.19
      - python: "3.3"
        env: DJANGO=1.7.11
      - python: "3.3"
        env: DJANGO=1.6.11
    exclude:
      - python: "3.4"
        env: DJANGO=1.6.11
install:
  - pip install -e .
  - pip install -r requirements/tests.txt Django==$DJANGO
script:
  - django-admin.py test --settings=app_metrics.tests.settings app_metrics
env:
  - DJANGO=1.6.11
  - DJANGO=1.7.11
  - DJANGO=1.8.19
  - DJANGO=1.9.13
  - DJANGO=1.10.8
  - DJANGO=1.11.13
