# Generated by Django 2.2.10 on 2020-03-22 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_metrics', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='metric',
            name='name',
            field=models.CharField(max_length=128, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='metric',
            name='slug',
            field=models.SlugField(max_length=128, unique=True, verbose_name='slug'),
        ),
    ]
